version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maydatabase
      POSTGRES_USER: user
      POSGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:

  frontend:

networks:
  mynetwork:
  

volumes:
  postgres_data